[package]
name = "teaclave_execution_service"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave worker."
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[dependencies]
env_logger  = { version = "0.7.1" }
anyhow      = { version = "1.0.26" }
libc        = { version = "0.2.66" }
signal-hook = { version = "0.1.13" }

teaclave_file_agent        = { path = "../../../file_agent" }
teaclave_service_app_utils = { path = "../../utils/service_app_utils" }
